#!/bin/bash

set -e

if [[ "$#" == "3" ]]; then
	echo "$3" > /etc/defaultdomain
	echo ypserver "$2" >> /etc/yp.conf

	sed -i 's/compat/compat\ nis/g' /etc/nsswitch.conf
	sed -i 's/dns/nis\ dns/g' /etc/nsswitch.conf

	mkdir -p /run/sendsigs.omit.d

	#domainname "$3"

	/etc/init.d/rpcbind start
	/etc/init.d/nis start
	
	LOCAL_NIS="$2 $3"
fi

NIS="${LOCAL_NIS}" /usr/local/lib/docklet-http/ftplib2-server.py &

WORK_ON="$1" NIS="${LOCAL_NIS}" /usr/local/lib/docklet-http/dl-httprest.py

