#!/bin/bash

set -e

if [[ "$#" == "3" ]]; then
	echo "$3" > /etc/defaultdomain
	echo ypserver "$2" >> /etc/yp.conf

	sed -i 's/compat/compat\ nis/g' /etc/nsswitch.conf
	sed -i 's/dns/nis\ dns/g' /etc/nsswitch.conf

	mkdir -p /run/sendsigs.omit.d

	#domainname "$3"

	/etc/init.d/rpcbind start
	/etc/init.d/nis start
	
	LOCAL_NIS="$2 $3"
fi

# NIS="${LOCAL_NIS}" /usr/local/lib/docklet-http/ftplib2-server.py &

# /usr/local/lib/docklet-http/wssh/dl-wssh -p 21 || true &


function setup {
	rm -rf /dev/console /dev/null /dev/zero /dev/tty /dev/random /dev/urandom
	mknod -m 622 /dev/console c 5 1
	mknod -m 666 /dev/null c 1 3
	mknod -m 666 /dev/zero c 1 5
	# rm -rf /dev/ptmx ; mknod -m 666 /dev/ptmx c 5 2
	mknod -m 666 /dev/tty c 5 0
	mknod -m 444 /dev/random c 1 8
	mknod -m 444 /dev/urandom c 1 9
}

setup

WORK_ON="$1" NIS="${LOCAL_NIS}" /usr/local/lib/docklet-http/dl-httprest.py

