#!/bin/bash

set -e

read -p 'Docklet Username: ' USERNAME

echo "${USERNAME}" | grep '^[a-zA-Z0-9]\{1,20\}$' >/dev/null 2>&1

read -p 'Password: ' -s PASSWORD

echo "${PASSWORD}" | grep '^[a-zA-Z0-9\-\_\.\@\(\)\=\+]\{1,20\}$' >/dev/null 2>&1

echo -e "\033[34m* Detecting users portal ..\033[0m" > /dev/stderr
PORTAL=$(curl -F user=${USERNAME} -F key=${PASSWORD} http://docklet.unias.org:8000/clusters 2>/dev/null | python -mjson.tool | grep portal.: | head -n 1 | awk -F\" '{print $4}')

[[ "${PORTAL}" != "" ]]

echo -e "\033[34m* Loading keys for openssh ..\033[0m" > /dev/stderr

SSH_KEY=$(curl -H "Auth:${USERNAME}/${PASSWORD}" http://docklet.unias.org:8000/user/login 2>/dev/null | python -mjson.tool | grep openssh.: | awk -F\" '{print $4}' | sed 's/\\n/\n/g')

[[ "${SSH_KEY}" != "" ]]

echo -e "\033[34m* Portal detected: ${PORTAL}, try to login ..\033[0m" >/dev/stderr

echo "${SSH_KEY}" > /tmp/${USERNAME}.key
chmod go-rw /tmp/${USERNAME}.key

ssh -i /tmp/${USERNAME}.key -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no root@${PORTAL}

echo -e "\033[34m* Connection reset by peer\033[0m" > /dev/stderr
