#!/bin/bash

set -e

[[ "$@" == "" ]] && exit 1

echo sei.pku.edu.cn > /etc/defaultdomain
echo ypserver 192.168.4.10 >> /etc/yp.conf

sed -i 's/compat/compat\ nis/g' /etc/nsswitch.conf
sed -i 's/dns/nis\ dns/g' /etc/nsswitch.conf

mkdir -p /run/sendsigs.omit.d

domainname sei.pku.edu.cn

/etc/init.d/rpcbind start
/etc/init.d/nis start

GROW_ON="$@" /usr/local/lib/docklet-http/docklet-http

